# Generated by Django 5.1.4 on 2024-12-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
