# Generated by Django 5.1.4 on 2024-12-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ['created'], 'verbose_name': 'Robot', 'verbose_name_plural': 'Robots'},
        ),
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
