# Generated by Django 5.1.4 on 2024-12-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_alter_robot_options_alter_robot_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
    ]
